#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : openpyxl
Version  : 2.5.02
Release  : 2
URL      : https://pypi.python.org/packages/5a/8b/798a853ef87d505392227b91d598fd0bdfc8552e64020092e262b1ea7d5f/openpyxl-2.5.0a2.tar.gz
Source0  : https://pypi.python.org/packages/5a/8b/798a853ef87d505392227b91d598fd0bdfc8552e64020092e262b1ea7d5f/openpyxl-2.5.0a2.tar.gz
Summary  : A Python library to read/write Excel 2010 xlsx/xlsm files
Group    : Development/Tools
License  : MIT
Requires: openpyxl-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
openpyxl
========
openpyxl is a Python library to read/write Excel 2010 xlsx/xlsm/xltx/xltm files.

%package python
Summary: python components for the openpyxl package.
Group: Default

%description python
python components for the openpyxl package.


%prep
%setup -q -n openpyxl-2.5.0a2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1498670946
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1498670946
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
